<?php
require_once("../../../conexion/conexiondwh.php");
##############################################################
echo("<br>");
echo ("radiacion_solar");
echo("<br>");
$consulta = "SELECT count(radiacion_solar) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(radiacion_solar) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("evapotranspiracion");
echo("<br>");
$consulta = "SELECT count(evapotranspiracion) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(evapotranspiracion) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("presion_barometrica");
echo("<br>");
$consulta = "SELECT count(presion_barometrica) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(presion_barometrica) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("direccion_viento");
echo("<br>");
$consulta = "SELECT count(direccion_viento) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(direccion_viento) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("velocidad_viento");
echo("<br>");
$consulta = "SELECT count(velocidad_viento) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(velocidad_viento) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("caudal");
echo("<br>");
$consulta = "SELECT count(caudal) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(caudal) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("nivel");
echo("<br>");
$consulta = "SELECT count(nivel) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(nivel) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("humedad_relativa");
echo("<br>");
$consulta = "SELECT count(humedad_relativa) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(humedad_relativa) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("brillo");
echo("<br>");
$consulta = "SELECT count(brillo) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
//$consulta_dos = "SELECT count(brillo) from central";
//$resultado_dos = pg_query($consulta_dos);
//$F_rese_dos= pg_fetch_array($resultado_dos);
//echo var_dump($F_rese_dos);
echo("No existe la columna brillo en central");
echo("<br>");
#################################################################
echo("<br>");
echo ("temperatura");
echo("<br>");
$consulta = "SELECT count(temperatura) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(temperatura) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("precipitacion");
echo("<br>");
$consulta = "SELECT count(precipitacion) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(precipitacion) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("tiempo_sk");
echo("<br>");
$consulta = "SELECT count(tiempo_sk) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(tiempo_sk) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("fecha_sk");
echo("<br>");
$consulta = "SELECT count(fecha_sk) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(fecha_sk) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
echo("<br>");
echo ("estacion_sk");
echo("<br>");
$consulta = "SELECT count(estacion_sk) from fact_table";
$resultado = pg_query($consulta);
$F_rese= pg_fetch_array($resultado);
echo var_dump($F_rese);
echo("<br>");
$consulta_dos = "SELECT count(estacion_sk) from central";
$resultado_dos = pg_query($consulta_dos);
$F_rese_dos= pg_fetch_array($resultado_dos);
echo var_dump($F_rese_dos);
echo("<br>");
#################################################################
?>
