<?php
return array(
	'BE' => array(
		'debug' => FALSE,
		'explicitADmode' => 'explicitAllow',
		'installToolPassword' => '$P$C5ZSVRunO2sqG99XAi2n2DHCHfOWM/0',
		'loginSecurityLevel' => 'normal',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'idea',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => 'ndcorpbod',
		'port' => 3306,
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'adx_twitter_bootstrap' => 'a:2:{s:11:"components.";a:8:{s:23:"activateResponsiveImage";s:1:"1";s:18:"activateTwoColumns";s:1:"1";s:20:"activateThreeColumns";s:1:"1";s:19:"activateFourColumns";s:1:"1";s:16:"activateCarousel";s:1:"1";s:12:"activateTabs";s:1:"1";s:17:"activateAccordion";s:1:"1";s:18:"activateDatepicker";s:1:"1";}s:11:"extensions.";a:1:{s:17:"activatePowermail";s:1:"1";}}',
			'bootstrap_core' => 'a:0:{}',
			'bootstrap_package' => 'a:3:{s:4:"Logo";s:84:"../typo3conf/ext/bootstrap_package/Resources/Public/Images/Backend/TopBarLogo@2x.png";s:9:"LoginLogo";s:80:"../typo3conf/ext/bootstrap_package/Resources/Public/Images/Backend/LoginLogo.png";s:16:"UseRealUrlConfig";s:1:"1";}',
			'bsdist' => 'a:0:{}',
			'fluidcontent_bootstrap' => 'a:0:{}',
			'flux' => 'a:4:{s:9:"debugMode";s:1:"0";s:15:"disableCompiler";s:1:"0";s:7:"compact";s:1:"0";s:12:"handleErrors";s:1:"0";}',
			'frsupersized' => 'a:1:{s:24:"useSelectInsteadCheckbox";s:1:"0";}',
			'introduction' => 'a:0:{}',
			'jfmulticontent' => 'a:16:{s:17:"useStoragePidOnly";s:1:"1";s:11:"ttNewsCodes";s:1:"1";s:16:"frontendErrorMsg";s:1:"1";s:24:"useSelectInsteadCheckbox";s:1:"0";s:22:"useOwnUserFuncForPages";s:1:"0";s:16:"openExternalLink";s:1:"0";s:16:"showEmptyContent";s:1:"0";s:14:"addBrowseLinks";s:1:"0";s:15:"tabSelectByHash";s:1:"0";s:19:"colPosOfIrreContent";s:2:"93";s:6:"style.";a:11:{s:7:"2column";s:1:"1";s:7:"3column";s:1:"1";s:7:"4column";s:1:"1";s:7:"5column";s:1:"1";s:3:"tab";s:1:"1";s:9:"accordion";s:1:"1";s:6:"slider";s:1:"1";s:9:"slidedeck";s:1:"1";s:13:"easyaccordion";s:1:"1";s:7:"booklet";s:1:"1";s:10:"typoscript";s:1:"1";}s:10:"classInner";s:36:",16,20,25,33,38,40,50,60,62,66,75,80";s:25:"anythingSliderThemeFolder";s:45:"EXT:jfmulticontent/res/anythingslider/themes/";s:23:"easyAccordionSkinFolder";s:43:"EXT:jfmulticontent/res/easyaccordion/skins/";s:19:"anythingSliderModes";s:24:"horizontal,vertical,fade";s:13:"updateMessage";s:1:"0";}',
			'macina_banners' => 'a:2:{s:25:"activateDefaultCategories";s:1:"1";s:10:"renderMode";s:9:"two_boxes";}',
			'operations' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'scheduler' => 'a:5:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";s:30:"listShowTaskDescriptionAsHover";s:1:"1";}',
			'vhs' => 'a:0:{}',
			'ws_less' => 'a:0:{}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'es',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'activateContentAdapter' => FALSE,
		'debug' => FALSE,
		'loginSecurityLevel' => 'normal',
	),
	'GFX' => array(
		'jpg_quality' => '80',
	),
	'MAIL' => array(
		'transport' => 'smtp',
		'transport_smtp_encrypt' => 'tls',
		'transport_smtp_password' => '4th3n34_cc',
		'transport_smtp_server' => '173.194.76.108:587',
		'transport_smtp_username' => 'idea_man@unal.edu.co',
	),
	'SYS' => array(
		'caching' => array(
			'cacheConfigurations' => array(
				'extbase_object' => array(
					'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
			),
		),
		'clearCacheSystem' => FALSE,
		'compat_version' => '6.2',
		'devIPmask' => '',
		'displayErrors' => FALSE,
		'enableDeprecationLog' => FALSE,
		'encryptionKey' => 'b80bb02014006f4a4779591ed921b604d31f4fe2bd196b239e39d3acfe27cee8e60a25bdde8a2093edd085539c849e65',
		'isInitialInstallationInProgress' => FALSE,
		'sitename' => 'IDEA',
		'sqlDebug' => 0,
		'systemLogLevel' => 2,
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
	),
);
?>
